#!/usr/bin/ansible-playbook

- hosts: localhost
  connection: local

  tasks:
    - name: Install packages
      include: tasks/packages.yml

    - name: Install fish
      include: tasks/fish.yml

    - name: User config
      include: tasks/user.yml

