---

- name: Copy tmux config
  copy:
    src: files/dotfiles/.tmux.conf
    dest: /etc/tmux.conf

- name: Copy fish config (root)
  copy:
    src: files/dotfiles/.config/fish/
    dest: /root/.config/fish/
    owner: root
    group: root

- name: File execution rights (root)
  file:
    path: /root/.config/fish/dist.sh
    mode: 0755

- name: Copy fish config (tuetuopay)
  copy:
    src: files/dotfiles/.config/fish/
    dest: /home/tuetuopay/.config/fish/
    owner: tuetuopay
    group: tuetuopay

- name: File execution rights (tuetuopay)
  file:
    path: /home/tuetuopay/.config/fish/dist.sh
    mode: 0755

- name: Copy vimrc (root)
  copy:
    src: files/dotfiles/.vimrc
    dest: /root/.vimrc
    owner: root
    group: root

- name: Copy vim folder (root)
  copy:
    src: files/dotfiles/.vim/
    dest: /root/.vim/
    owner: root
    group: root

- name: Install vim plugins (root)
  command: vim -c ":PlugInstall | :qa"

- name: Copy vimrc (tuetuopay)
  copy:
    src: files/dotfiles/.vimrc
    dest: /home/tuetuopay/.vimrc
    owner: tuetuopay
    group: tuetuopay

- name: Copy vim folder (tuetuopay)
  copy:
    src: files/dotfiles/.vim/
    dest: /home/tuetuopay/.vim/
    owner: tuetuopay
    group: tuetuopay

- name: Install vim plugins (tuetuopay)
  command: su tuetuopay -c 'vim -c ":PlugInstall | :qa"'

- name: Add SSH keys
  copy:
    src: files/dotfiles/.ssh/authorized_keys
    dest: /home/tuetuopay/.ssh/authorized_keys
    mode: 0600
    owner: tuetuopay
    group: tuetuopay

