---

- name: Setup EPEL
  yum:
    name: epel-release
    state: present

- name: Setup htop
  yum:
    name: htop
    state: present

- name: Setup vim
  yum:
    name: vim
    state: present

- name: Setup tmux
  yum:
    name: tmux
    state: present

- name: Setup Docker
  yum:
    name: docker-engine
    state: present

- name: Run docker at boot
  systemd:
    name: docker
    enabled: yes

- name: Setup certbot
  yum:
    name: certbot
    state: present

- name: Setup glances
  yum:
    name: glances
    state: present

- name: Setup yum-cron
  yum:
    name: yum-cron
    state: present

