---

- name: Update all system package
  yum:
    name: '*'
    state: latest

- name: Setup EPEL
  yum:
    name: epel-release
    state: present

- name: Setup htop, vim, tmux, docker, certbot, glances, yum-cron
  yum:
    name:
      - htop
      - vim
      - tmux
      - docker
      - certbot
      - glances
      - yum-cron
    state: latest

- name: Run docker at boot
  systemd:
    name: docker
    enabled: yes

- name: Configure yum-cron
  copy:
    src: files/yum-cron.conf
    dest: /etc/yum/yum-cron.conf

- name: Set yum-cron email address
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: '^email_to'
    line: 'email_to = {{ email_user }}@{{ email_domain }}'

