---

- name: Setup docker group
  group:
    name: docker
    state: present

- name: Create my user
  user:
    name: tuetuopay
    generate_ssh_key: yes
    ssh_key_bits: 4096
    shell: /usr/bin/fish
    state: present
    groups:
      - wheel
      - docker

- name: Add it to sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'tuetuopay ALL=(ALL) ALL'

